version: '3.9'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports: ["5435:5432"]
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_wal_senders=10"
      - "-c"
      - "max_replication_slots=10"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_sub:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports: ["5436:5432"]
    depends_on: [postgres]
    volumes:
      - postgres_sub_data:/var/lib/postgresql/data

  pgbackups:
    image: bash
    volumes:
      - ./backup.sh:/backup.sh
      - ./dumps:/dumps
    depends_on:
      - postgres
    entrypoint: [ "bash", "-lc", "while true; do /backup.sh; sleep 86400; done" ]

  mongodb:
    image: mongo:6
    container_name: library_mongo
    restart: always
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      # Подключаемся к твоему первому сервису 'postgres'
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable"
    depends_on:
      - postgres

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - postgres-exporter

  grafana:
    image: grafana/grafana
    container_name: library_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
  
  mongodb-exporter:
    image: percona/mongodb_exporter:0.40
    container_name: library_mongo_exporter
    command:
      - '--mongodb.uri=mongodb://test:testing@library_mongo:27017/admin?replicaSet=rs0'
      - '--collect-all'
      - '--compatible-mode'
    ports:
      - "9216:9216"
    depends_on:
      - mongodb

  redis:
    image: redis:7-alpine
    container_name: library_redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data:
  mongo_data:
  postgres_sub_data:
