ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"

db:
  postgres:
    jdbcDriver: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5435/postgres"
    user: postgres
    password: postgres
    maxPoolSize: 5
  mongo:
    user: mongo
    password: mongo
    host: localhost
    port: 27018
    database:
      name: library

flyway:
  clean: false