{
 "title": "Neo4j — Library",
 "tags": [
  "neo4j",
  "library"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "panels": [
  { "title": "Подсказка", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "Neo4j Metrics." } },
  {
   "title": "Neo4j Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "neo4j_up" }
   ]
  },
  {
   "title": "Узлов в графе",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "neo4j_nodes_total" }
   ]
  },
  {
   "title": "Связей в графе",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "neo4j_relationships_total" }
   ]
  },
  {
   "title": "Число узлов во времени",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "neo4j_nodes_total", "legendFormat": "узлы" }
   ]
  },
  {
   "title": "Число связей во времени",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "neo4j_relationships_total", "legendFormat": "связи" }
   ]
  },
  {
   "title": "Скрейпы в минуту (график меняется)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(neo4j_scrapes_total[1m])*60",
     "legendFormat": "скрейпов/мин"
    }
   ]
  },
  {
   "title": "Длительность сбора метрик (меняется)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "neo4j_scrape_duration_seconds", "legendFormat": "сек" }
   ]
  },
  {
   "title": "Время последнего скрейпа",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "targets": [
    {
     "expr": "neo4j_last_scrape_timestamp_seconds",
     "legendFormat": "последний скрейп"
    }
   ]
  }
 ]
}